spring:
  application:
    name: findex
  datasource:
    url: jdbc:postgresql://shinkansen.proxy.rlwy.net:29706/railway?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace

springdoc:
  open-api:
    base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
    service-key: ${OPEN_API_SERVICE_KEY}