spring:
  application:
    name: findex

  datasource:                                               # 데이터베이스 연결
    url: jdbc:postgresql://shinkansen.proxy.rlwy.net:29706/railway?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
  jpa:                                                      # JPA 설정
    hibernate:
      ddl-auto: update                                      # 테이블 - 엔티티 일치 여부
    show-sql: true                                          # SQL 실행문 보기
    properties:                                             # SQL 로그 설정
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  sql:                                                      # SQL 초기화
    init:
      mode: always                                          # 애플리케이션 시작 시, 항상 실행

logging:                                                    # 로깅 설정값
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace

data-portal:                                                # 공공데이터포털 Open API 설정
  market-index:
    base-url: https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService
    service-key: ${OPEN_API_SERVICE_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    groups-order: ASC
    operations-sorter: alpha